use utoipa::{
    OpenApi,
    openapi::{self, Contact},
};

use crate::models::user::{LoginUser, NewUser};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::controllers::activity::api_list_activity,
        crate::controllers::activity::api_record_edit,
        crate::controllers::admin::api_get_admin_stats,
        crate::controllers::admin::api_get_admin_users,
        crate::controllers::admin::api_get_admin_teams,
        crate::controllers::admin::api_admin_search,
        crate::controllers::admin::api_admin_notify,
        crate::controllers::admin::api_get_admin_notebooks,
        crate::controllers::challenge::api_list_challenges,
        crate::controllers::challenge::api_get_challenge,
        crate::controllers::challenge::api_get_challenge_by_id,
        crate::controllers::challenge::api_create_challenge,
        crate::controllers::challenge::api_update_challenge,
        crate::controllers::challenge::api_add_test_case,
        crate::controllers::challenge::api_set_reference,
        crate::controllers::challenge::api_get_reference,
        crate::controllers::challenge::api_delete_reference,
        crate::controllers::challenge::api_list_test_cases,
        crate::controllers::challenge::api_delete_test_case,
        crate::controllers::challenge::api_submit,
        crate::controllers::challenge::api_run_samples,
        crate::controllers::challenge::api_get_submission,
        crate::controllers::challenge::api_list_my_submissions,
        crate::controllers::challenge::api_leaderboard,
        crate::controllers::chat::api_list_notebook_messages,
        crate::controllers::chat::api_send_notebook_message,
        crate::controllers::chat::api_edit_notebook_message,
        crate::controllers::chat::api_edit_team_message,
        crate::controllers::chat::api_delete_notebook_message,
        crate::controllers::chat::api_delete_team_message,
        crate::controllers::chat::api_list_notebook_message_versions,
        crate::controllers::chat::api_list_team_message_versions,
        crate::controllers::chat::api_list_team_messages,
        crate::controllers::chat::api_send_team_message,
        crate::controllers::comments::api_list_comments,
        crate::controllers::comments::api_create_thread,
        crate::controllers::comments::api_reply,
        crate::controllers::comments::api_update_thread,
        crate::controllers::comments::api_delete_comment,
        crate::controllers::folder::api_list_folders,
        crate::controllers::folder::api_create_folder,
        crate::controllers::folder::api_rename_folder,
        crate::controllers::folder::api_update_folder_tags,
        crate::controllers::folder::api_delete_folder,
        crate::controllers::folder::api_move_notebook_to_folder,
        crate::controllers::folder::api_list_team_folders,
        crate::controllers::folder::api_create_team_folder,
        crate::controllers::folder::api_rename_team_folder,
        crate::controllers::folder::api_update_team_folder_tags,
        crate::controllers::folder::api_delete_team_folder,
        crate::controllers::grants::api_list_team_grants,
        crate::controllers::grants::api_create_team_grant,
        crate::controllers::grants::api_delete_team_grant,
        crate::controllers::grants::api_list_public_grants,
        crate::controllers::grants::api_create_public_grant,
        crate::controllers::grants::api_delete_public_grant,
        crate::controllers::notebook::api_create_notebook,
        crate::controllers::notebook::api_get_notebooks,
        crate::controllers::notebook::api_get_single_notebook,
        crate::controllers::notebook::api_rename_notebook,
        crate::controllers::notebook::api_update_notebook_tags,
        crate::controllers::notebook::api_update_notebook_visibility,
        crate::controllers::notebook::api_delete_notebook,
        crate::controllers::notebook::api_get_single_notebook_with_blocks,
        crate::controllers::notebook::api_save_notebook_content,
        crate::controllers::notebook::api_clone_notebook,
        crate::controllers::notebook::api_search_notebooks,
        crate::controllers::notebook::api_search_notebooks_ranked,
        crate::controllers::notebook::api_get_public_notebook_by_slug,
        crate::controllers::notebook::api_get_public_notebooks,
        crate::controllers::notifications::api_list_notifications,
        crate::controllers::notifications::api_mark_notification_read,
        crate::controllers::notifications::api_mark_all_read,
        crate::controllers::notifications::api_delete_notification,
        crate::controllers::notifications::api_list_preferences,
        crate::controllers::notifications::api_upsert_preference,
        crate::controllers::oauth::api_oauth_login,
        crate::controllers::oauth::api_link_start,
        crate::controllers::oauth::api_oauth_callback,
        crate::controllers::oauth::api_link_callback,
        crate::controllers::oauth::api_unlink,
        crate::controllers::oauth::api_auth_methods,
        crate::controllers::oauth::api_auth_providers,
        crate::controllers::permissions::api_get_permission_catalog,
        crate::controllers::permissions::api_get_team_capabilities,
        crate::controllers::permissions::api_get_notebook_capabilities,
        crate::controllers::push::api_subscribe_push,
        crate::controllers::push::api_unsubscribe_push,
        crate::controllers::snapshots::api_list_snapshots,
        crate::controllers::snapshots::api_create_snapshot,
        crate::controllers::snapshots::api_restore_snapshot,
        crate::controllers::snapshots::api_delete_snapshot,
        crate::controllers::team::api_create_team_page,
        crate::controllers::team::api_get_team_pages,
        crate::controllers::team::api_update_team,
        crate::controllers::team::api_get_team_roles,
        crate::controllers::team::api_create_team_role,
        crate::controllers::team::api_get_user_teams,
        crate::controllers::team::api_update_team_role,
        crate::controllers::team::api_remove_user_from_team,
        crate::controllers::team::api_update_member_role,
        crate::controllers::team::api_get_team_members,
        crate::controllers::team::api_get_team,
        crate::controllers::team::api_delete_team,
        crate::controllers::team::api_create_team,
        crate::controllers::team::api_get_user_team_permissions,
        crate::controllers::team_invitation::api_invite_member,
        crate::controllers::team_invitation::api_accept_invite,
        crate::controllers::template::api_create_template,
        crate::controllers::template::api_publish_version,
        crate::controllers::template::api_get_template,
        crate::controllers::template::api_list_my_templates,
        crate::controllers::template::api_list_public_templates,
        crate::controllers::template::api_update_template_visibility,
        crate::controllers::template::api_delete_template,
        crate::controllers::user::api_register_user,
        crate::controllers::user::api_login_user,
        crate::controllers::user::api_refresh_session,
        crate::controllers::user::api_logout,
        crate::controllers::user::api_update_user_data,
        crate::controllers::user::api_get_logged_user,
        crate::controllers::user::api_delete_user,
        crate::controllers::user::api_update_user_password,
        crate::controllers::user::api_get_user_notebook_permissions,
        crate::controllers::user::api_request_password_reset,
        crate::controllers::user::api_execute_password_reset,
        crate::http::verify_request,
        crate::http::verify_go_request,
        crate::http::verify_cpp_request,
        crate::http::verify_zig_request,
    ),
    components(schemas(
        NewUser,
        LoginUser,
        crate::models::error::ApiError,
        crate::CodeResponse
    ))
)]
pub struct ApiDoc;

pub fn get_api_docs() -> openapi::OpenApi {
    let mut docs = ApiDoc::openapi();
    let mut contact = Contact::new();
    contact.email = Some("hadsonramalho@gmail.com".to_string());
    contact.name = Some("Hadson Ramalho".to_string());
    contact.url = Some("https://github.com/HadsonRamalho".to_string());
    docs.info.contact = Some(contact);
    docs.info.license = None;
    docs.info.title = "Rust Backend Template".to_string();
    docs.info.version = "0.1.0".to_string();
    docs.info.extensions = None;
    docs.info.terms_of_service = None;
    docs.external_docs = None;

    docs
}
