import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import type {
  CapabilitySnapshot,
  GrantEffect,
  GrantView,
  PermissionCatalog,
  PermissionTarget,
  PermissionTargetKind,
} from "@/lib/types/permission-types";
import { buildImpliedIndex, can } from "./engine";

const SNAPSHOT_PATH = resolve(
  import.meta.dirname,
  "../../contracts/permission-catalog.json",
);

const NIL_UUID = "00000000-0000-0000-0000-000000000000";

let catalog: PermissionCatalog;
let implied: Map<string, string[]>;

beforeAll(() => {
  catalog = JSON.parse(
    readFileSync(SNAPSHOT_PATH, "utf8"),
  ) as PermissionCatalog;
  implied = buildImpliedIndex(catalog);
});

function grant(
  key: string,
  effect: GrantEffect,
  kind: PermissionTargetKind,
  value: string | null = null,
): GrantView {
  return {
    permissionKey: key,
    effect,
    targetKind: kind,
    targetId: kind === "notebook" ? NIL_UUID : null,
    targetValue: value,
  };
}

function caps(grants: GrantView[], all = false): CapabilitySnapshot {
  return { all, grants };
}

const defaultTarget: PermissionTarget = { notebookId: NIL_UUID };

function blockType(kind: string): PermissionTarget {
  return { notebookId: NIL_UUID, blockType: kind };
}

describe("catalog snapshot", () => {
  it("loads permissions from the file generated by Rust", () => {
    expect(catalog.permissions.length).toBeGreaterThan(0);
  });

  it("contains the keys that the parity cases exercise", () => {
    const keys = new Set(catalog.permissions.map((p) => p.key));
    for (const key of [
      "notebook.view",
      "notebook.edit",
      "notebook.delete",
      "notebook.blocks.view",
      "notebook.blocks.execute",
      "notebook.blocks.rust.view",
      "notebook.blocks.rust.execute",
      "notebook.blocks.go.view",
    ]) {
      expect(keys, `chave ausente no snapshot: ${key}`).toContain(key);
    }
  });

  it("preserves the implied_by relationship that key expansion depends on", () => {
    const rustExecute = catalog.permissions.find(
      (p) => p.key === "notebook.blocks.rust.execute",
    );
    expect(rustExecute?.impliedBy).toContain("notebook.blocks.execute");
  });
});

describe("paridade com controllers::permissions::tests", () => {
  it("default_deny_when_no_grants", () => {
    expect(can(caps([]), implied, "notebook.view", defaultTarget)).toBe(false);
  });

  it("general_grant_implies_granular", () => {
    const c = caps([grant("notebook.blocks.execute", "allow", "team")]);
    expect(can(c, implied, "notebook.blocks.rust.execute", defaultTarget)).toBe(
      true,
    );
  });

  it("deny_beats_allow_at_same_level", () => {
    const c = caps([
      grant("notebook.view", "allow", "team"),
      grant("notebook.view", "deny", "team"),
    ]);
    expect(can(c, implied, "notebook.view", defaultTarget)).toBe(false);
  });

  it("more_specific_allow_overrides_broader_deny", () => {
    const c = caps([
      grant("notebook.blocks.view", "deny", "team"),
      grant("notebook.blocks.rust.view", "allow", "block_type", "rust"),
    ]);
    expect(
      can(c, implied, "notebook.blocks.rust.view", blockType("rust")),
    ).toBe(true);
  });

  it("block_type_deny_hides_only_that_type", () => {
    const c = caps([
      grant("notebook.blocks.view", "allow", "team"),
      grant("notebook.blocks.go.view", "deny", "block_type", "go"),
    ]);
    expect(can(c, implied, "notebook.blocks.go.view", blockType("go"))).toBe(
      false,
    );
    expect(
      can(c, implied, "notebook.blocks.rust.view", blockType("rust")),
    ).toBe(true);
  });

  it("public_baseline_allows_view_not_edit", () => {
    const c = caps([grant("notebook.view", "allow", "notebook")]);
    expect(can(c, implied, "notebook.view", defaultTarget)).toBe(true);
    expect(can(c, implied, "notebook.edit", defaultTarget)).toBe(false);
  });

  it("owner_can_everything", () => {
    const c = caps([], true);
    expect(can(c, implied, "notebook.delete", defaultTarget)).toBe(true);
  });
});
